; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Sarbaz"
#define MyAppVersion "1.0.3"
#define MyAppPublisher "MohraTech Company, Inc."
#define MyAppURL "http://www.mohratech.ir/"
#define MyAppExeName "sarbaz.exe"
; Custom vars
#define MyAppReleaseFolder "C:\sarbaz\build\windows\runner\Release"
#define MyAppExternalLibsSourceFolder "C:\sarbaz\assets\external_libs"
#define MyAppInstallaionFolder "C:\Program Files\Sarbaz"
#define MyAppLibsFolder "C:\Program Files\Sarbaz\libs"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B8B3EEFE-3A3A-4988-B543-72DFC13113AB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={#MyAppInstallaionFolder}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=C:\sarbaz\windows\InnoSetupFiles
OutputBaseFilename={#MyAppName}_v{#MyAppVersion}
SetupIconFile=C:\sarbaz\windows\InnoSetupFiles\military_hat.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppReleaseFolder}\{#MyAppExeName}"; DestDir: "{#MyAppInstallaionFolder}"; Flags: ignoreversion
Source: "{#MyAppReleaseFolder}\data\*"; DestDir: "{#MyAppInstallaionFolder}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#MyAppReleaseFolder}\flutter_windows.dll"; DestDir: "{#MyAppInstallaionFolder}"; Flags: ignoreversion
Source: "{#MyAppReleaseFolder}\sqlite3.dll"; DestDir: "{#MyAppInstallaionFolder}"; Flags: ignoreversion
Source: "{#MyAppReleaseFolder}\sqlite3_flutter_libs_plugin.dll"; DestDir: "{#MyAppInstallaionFolder}"; Flags: ignoreversion
Source: "{#MyAppExternalLibsSourceFolder}\sqlite3.def"; DestDir: "{#MyAppLibsFolder}\sqlite3"; Flags: ignoreversion
Source: "{#MyAppExternalLibsSourceFolder}\sqlite3.dll"; DestDir: "{#MyAppLibsFolder}\sqlite3"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

