library components;

import 'dart:core';

import 'package:dotted_border/dotted_border.dart';
import 'package:eva_icons_flutter/eva_icons_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_styled_toast/flutter_styled_toast.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:loading_animation_widget/loading_animation_widget.dart';
import 'package:percent_indicator/linear_percent_indicator.dart';
import 'package:persian_tools/persian_tools.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'package:timeago/timeago.dart' as timeago;

import 'package:sarbaz/app/src/controllers/controllers.dart';
import 'package:sarbaz/core/src/config/config.dart';
import 'package:sarbaz/core/src/models/models.dart';
import 'package:sarbaz/utility/utility.dart';

import '../themes/themes.dart';

part 'dialogs/dialog_helper.dart';
part 'tables/models/soldier_data_cell_model.dart';
part 'tables/soldiers_data_table.dart';
part 'widgets/bottom_navbar.dart';
part 'widgets/case_no_tile.dart';
part 'widgets/contact_tile.dart';
part 'widgets/filled_button.dart';
part 'widgets/form_card.dart';
part 'widgets/group_box.dart';
part 'widgets/header_text.dart';
part 'widgets/image_view_personal_pic.dart';
part 'widgets/inner_view.dart';
part 'widgets/list_task_assigned.dart';
part 'widgets/list_task_date.dart';
part 'widgets/main_menu.dart';
part 'widgets/main_menu_selection_button.dart';
part 'widgets/member.dart';
part 'widgets/navbar_widget.dart';
part 'widgets/recent_activities.dart';
part 'widgets/recent_activities_header.dart';
part 'widgets/responsive_builder.dart';
part 'widgets/search_field.dart';
part 'widgets/simple_selection_button.dart';
part 'widgets/simple_user_profile.dart';
part 'widgets/status_card.dart';
part 'widgets/status_cards_overview.dart';
part 'widgets/tab_menu.dart';
part 'widgets/task_group.dart';
part 'widgets/task_menu.dart';
part 'widgets/text_box.dart';
part 'widgets/toast.dart';
part 'widgets/unit_soldiers_overview_progress_bar.dart';
part 'widgets/user_profile.dart';
part 'tables/models/daily_vacation_data_cell_model.dart';
part 'tables/daily_vacations_data_table.dart';
