name: sarbaz
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Internationalization support.
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  injectable: ^1.5.3
  intl: ^0.17.0
  logging: ^1.0.1
  drift: ^1.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  # add get_it  
  get_it: ^7.2.0
  json_serializable: ^6.1.4
  persian_tools: ^1.0.1
  iconsax: ^0.0.8
  percent_indicator: ^3.4.0
  dotted_border: ^2.0.0+1
  timeago: ^3.1.0
  eva_icons_flutter: ^3.0.2
  shamsi_date: ^1.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  floor_generator:
  build_runner:
  injectable_generator:
  drift_dev: ^1.2.0
 
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
   

  fonts:
    - family: Sahel
      fonts:
        - asset: assets/fonts/sahel/sahel.ttf
        - asset: assets/fonts/sahel/sahel_bold.ttf
        - asset: assets/fonts/sahel/sahel_black.ttf
        - asset: assets/fonts/sahel/sahel_light.ttf
        - asset: assets/fonts/sahel/sahel_semi_bold.ttf
