library models;

import 'package:json_annotation/json_annotation.dart';

part 'models/contact_info_model.dart';
part 'models/daily_vacation_model.dart';
part 'models/educational_info_model.dart';
part 'models/further_info_model.dart';
part 'models/health_status_model.dart';
part 'models/hourly_vacations_model.dart';
part 'models/personal_info_model.dart';
part 'models/rank_model.dart';
part 'models/section_model.dart';
part 'models/service_deficit_model.dart';
part 'models/soldier_case_model.dart';
part 'models/soldier_model.dart';
part 'models/training_status_model.dart';
part 'models/unit_properties_model.dart';
part 'models/vacations_model.dart';
part 'models/overtime_model.dart';
part 'models/disciplinary_overtime_model.dart';
part 'models/annual_overtime_model.dart';
part 'models/violations_overtime_model.dart';
part 'models/daily_absence_overtime_model.dart';
part 'models/service_deficit_record_model.dart';
part 'models/operational_service_deficit_model.dart';
part 'models/case_model.dart';
part 'models/relative_contacts_info_table.dart';
part 'models.g.dart';