library widgets;

import 'package:dotted_border/dotted_border.dart';
import 'package:eva_icons_flutter/eva_icons_flutter.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:percent_indicator/linear_percent_indicator.dart';
import 'package:persian_tools/persian_tools.dart';
import 'package:sarbaz/core/src/models/models.dart';
import 'package:sarbaz/utility/utility.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:timeago/timeago.dart' as timeago;

import '../themes/themes.dart';

part 'bottom_navbar.dart';
part 'date_picker_widget.dart';
part 'dialogs/message_dialog.dart';
part 'filled_button.dart';
part 'header_text.dart';
part 'header_weekly_task.dart';
part 'list_task_assigned.dart';
part 'list_task_date.dart';
part 'main_menu.dart';
part 'member.dart';
part 'navbar_widget.dart';
part 'responsive_builder.dart';
part 'search_field.dart';
part 'selection_button.dart';
part 'simple_selection_button.dart';
part 'simple_user_profile.dart';
part 'status_card.dart';
part 'task_group.dart';
part 'status_cards_overview.dart';
part 'task_menu.dart';
part 'unit_soldiers_overview_progress_bar.dart';
part 'user_profile.dart';
part 'weekly_task.dart';
part 'group_box.dart';
part 'soldiers_data_table.dart';